// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqEFr4MD_kmI4m9lrEDY7R43X_oYXDKoc',
    appId: '1:78082847734:web:bfc7a6b30de8a2f526cdd7',
    messagingSenderId: '78082847734',
    projectId: 'expens-mang',
    authDomain: 'expens-mang.firebaseapp.com',
    storageBucket: 'expens-mang.firebasestorage.app',
    measurementId: 'G-RYJ4PE3RJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgPuzHYHYe9zTf2QundnEqz4164bIrDOo',
    appId: '1:78082847734:android:a4a72a07d185a12d26cdd7',
    messagingSenderId: '78082847734',
    projectId: 'expens-mang',
    storageBucket: 'expens-mang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDjV6o028nEgC9vUF_d8DmHcQjVjk0pMk',
    appId: '1:78082847734:ios:526ef804ebd34b1c26cdd7',
    messagingSenderId: '78082847734',
    projectId: 'expens-mang',
    storageBucket: 'expens-mang.firebasestorage.app',
    iosBundleId: 'com.example.monussTry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDjV6o028nEgC9vUF_d8DmHcQjVjk0pMk',
    appId: '1:78082847734:ios:526ef804ebd34b1c26cdd7',
    messagingSenderId: '78082847734',
    projectId: 'expens-mang',
    storageBucket: 'expens-mang.firebasestorage.app',
    iosBundleId: 'com.example.monussTry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqEFr4MD_kmI4m9lrEDY7R43X_oYXDKoc',
    appId: '1:78082847734:web:c65f7922dc32a11d26cdd7',
    messagingSenderId: '78082847734',
    projectId: 'expens-mang',
    authDomain: 'expens-mang.firebaseapp.com',
    storageBucket: 'expens-mang.firebasestorage.app',
    measurementId: 'G-5LXZ1KT0RK',
  );
}
