name: Deploy Flutter Web and Build APK

on:
  push:
    branches:
      - main
      - build-apk-feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Flutter-ന്റെ കൃത്യമായ പുതിയ Stable Version കൊടുത്തു
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Linter
        run: flutter analyze || true

      - name: Run Unit Tests
        run: flutter test || true

      # 1. Flutter Web Build
      - name: Build Web
        run: flutter build web --release --base-href "/monus_try/"

      # 2. Flutter Android APK Build
      - name: Build Android APK
        run: flutter build apk --release

      # Web Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: Peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

      # Save Android APK as Artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk